name: Lint

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint Format Check
        run: pnpm lint:prettier

      - name: Check Build Packages
        run: pnpm build --filter=./packages/*

      - name: Check Types
        run: pnpm types:check

      - name: Run ESLint
        run: pnpm lint
