name: Lint

on:
  push:
    branches:
      - main
      - next
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint Format Check
        run: pnpm lint:prettier

      - name: Check Build Packages
        run: pnpm build --filter=./packages/*

      - name: Check Types
        run: pnpm types:check

      - name: Run ESLint
        run: pnpm lint
